# docker-compose.yml


services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      # --- LINHA ADICIONADA ---
      # Esta linha preserva a pasta node_modules que foi criada no build.
      - node_modules:/app/theme/static_src/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

# --- SEÇÃO MODIFICADA ---
volumes:
  postgres_data:
  node_modules: {} # Declaração do nosso novo volume