# render.yaml - Versão Minimalista e Final

services:
  # Serviço 1: O Banco de Dados PostgreSQL
  - type: pserv
    name: portfolio-db
    plan: free
    # Removemos a versão e a região. Deixamos o Render usar
    # os padrões do plano gratuito, que é o que ele espera.

  # Serviço 2: A Aplicação Web (Django)
  - type: web
    name: portfolio-web
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.13"