# render.yaml - Adicionando o diretório raiz

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free

services:
  - type: web
    name: portfolio-web
    runtime: python
    plan: free
    rootDir: backend # <-- A LINHA MÁGICA! Avisa ao Render onde nosso projeto Django começa.
    buildCommand: |
      pip install --no-cache-dir -r ../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.13"
      - key: DEBUG
        value: 0