# render.yaml - Versão com o tipo de serviço CORRETO

services:
  # Serviço 1: O Banco de Dados PostgreSQL
  - type: psql # <-- A CORREÇÃO ESTÁ AQUI. 'psql' em vez de 'pserv'.
    name: portfolio-db
    plan: free
    postgresMajorVersion: 15 

  # Serviço 2: A Aplicação Web (Django)
  - type: web
    name: portfolio-web
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.13"