# Generated by Django 5.2.3 on 2025-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente, não preencher.', unique=True)),
                ('cover', models.ImageField(upload_to='project_covers/', verbose_name='Capa do Projeto')),
                ('description', models.TextField(verbose_name='Descrição (suporta Markdown)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL do Vídeo (YouTube, Vimeo)')),
                ('tech_details', models.TextField(verbose_name='Detalhes Técnicos')),
                ('code_snippet', models.TextField(verbose_name='Trecho de Código')),
                ('code_language', models.CharField(default='python', max_length=50, verbose_name='Linguagem do Código')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='URL do Projeto/Repositório')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
