# Generated by Django 5.2.3 on 2025-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/', verbose_name='Ou Envie um Vídeo (MP4)'),
        ),
    ]
