# Generated by Django 5.2.3 on 2025-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='code_snippet',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Repositório no GitHub'),
        ),
    ]
